### ISSUE TITLE
error when run vault.bat on windows

### ISSUE THREAD

**Issue by lkjk113** [web-servers/tomcat-vault#63]
![image](https://user-images.githubusercontent.com/30855613/53539129-4c49c600-3b4b-11e9-978f-6e6c67f1b0a5.png)
Please have a look thank you!

**Comment by csutherl** [comment]
Hi @lkjk113 which version of vault are you using? How did you install? I built from master and tested it on windows and I don't see any issues. I'm using jdk-1.8.0u211.

**Comment by csutherl** [comment]
It's noteworthy that the `o.a.commons.cli.ParseException` class is bundled in the `tomcat-vault.jar`.

**Comment by csutherl** [comment]
Closing this as it works for me and there's been no update from @lkjk113. We can reopen it later if the issue persists.
